### PR TITLE
Heroku deploy

### PR DESCRIPTION
**Pull request by josemotanet**
Hi Atik,

Here's the summary of what I found out:
1. I rescued all exceptions from the routes. Since there are no pages nor default settings when deploying, loading the Rails environment to precompile the assets or migrate the database later, there would be errors.
2. Also, there would be an issue when visiting an empty CMS. There are no menus to begin with. I've added an `if` condition to address that situation.

Other than these, a couple of bugs and tweaks. Let me know if these work for you.

### CODE REVIEW

**Comment by atikp** [comment]
Hi jose,

Thank you ever so much for doing that for me. You do not understand how happy i am that you have taken your time to make this work for me. if there is anything i can do to repay the favour please let me know.

I have deployed it to Heroku successfully but when i try and access it it goes to a 404 page that it doesn't exist. please feel free to try it out.

 http://cmsrailsatikp.herokuapp.com/

are there any further steps i need to take eg: heroku rake db:migrate or something? i've even tried using the /categories/2 path as that is what i set as the homepage in the localhost server.

i know i'm asking a lot but

please advise

thank you again

kindest regards

Atik Patel

**Comment by josemotanet** [comment]
Did you by any chance forget to type `heroku run rake cms:bootstrap` so the
default settings are inserted?

Also, if you wanna know what's going on in your server through the logs, type
`heroku logs`.

> On Jan 27 2016, at 2:31 am, atikp &lt;notifications@github.com&gt; wrote:  
> Hi jose,  

Thank you ever so much for doing that for me. You do not understand how happy
i am that you have taken your time to make this work for me. if there is
anything i can do to repay the favour please let me know.  

I have deployed it to Heroku successfully but when i try and access it it goes
to a 404 page that it doesn't exist. please feel free to try it out.  

http://cmsrailsatikp.herokuapp.com/  

are there any further steps i need to take eg: heroku rake db:migrate or
something? i've even tried using the /categories/2 path as that is what i set
as the homepage in the localhost server.  

i know i'm asking a lot but  

please advise  

thank you again  

kindest regards  

Atik Patel

**Comment by atikp** [comment]
Hi José,
I didn't deploy the app through heroku toolbelt. It was via the github route.
I will try to redoploy using toolbelt now. Do I enter in the default command before or after I deploy?

Atik

Sent from Outlook Mobilehttps://aka.ms/blhgte

On Wed, Jan 27, 2016 at 2:17 AM -0800, "José Mota" <notifications@github.com<mailto:notifications@github.com>> wrote:

Did you by any chance forget to type `heroku run rake cms:bootstrap` so the
default settings are inserted?

Also, if you wanna know what's going on in your server through the logs, type
`heroku logs`.

> On Jan 27 2016, at 2:31 am, atikp &lt;notifications@github.com&gt; wrote:
> Hi jose,

Thank you ever so much for doing that for me. You do not understand how happy
i am that you have taken your time to make this work for me. if there is
anything i can do to repay the favour please let me know.

I have deployed it to Heroku successfully but when i try and access it it goes
to a 404 page that it doesn't exist. please feel free to try it out.

http://cmsrailsatikp.herokuapp.com/

are there any further steps i need to take eg: heroku rake db:migrate or
something? i've even tried using the /categories/2 path as that is what i set
as the homepage in the localhost server.

i know i'm asking a lot but

please advise

thank you again

kindest regards

Atik Patel

**Comment by josemotanet** [comment]
It should be after the deploy is performed.

> On Jan 27 2016, at 2:47 pm, atikp &lt;notifications@github.com&gt; wrote:  
Hi José,  
I didn't deploy the app through heroku toolbelt. It was via the github route.  
I will try to redoploy using toolbelt now. Do I enter in the default command
before or after I deploy?  
  
Atik  
  
Sent from Outlook Mobile&lt;https://aka.ms/blhgte&gt;  
  
  
  
On Wed, Jan 27, 2016 at 2:17 AM -0800, "José Mota"
&lt;notifications@github.com&lt;mailto:notifications@github.com&gt;&gt; wrote:  
  
Did you by any chance forget to type `heroku run rake cms:bootstrap` so the  
default settings are inserted?  
  
  
  
Also, if you wanna know what's going on in your server through the logs, type  
`heroku logs`.  
  
&gt; On Jan 27 2016, at 2:31 am, atikp
&amp;lt;notifications@github.com&amp;gt; wrote:  
Hi jose,  
  
  
Thank you ever so much for doing that for me. You do not understand how happy  
i am that you have taken your time to make this work for me. if there is  
anything i can do to repay the favour please let me know.  
  
  
I have deployed it to Heroku successfully but when i try and access it it goes  
to a 404 page that it doesn't exist. please feel free to try it out.  
  
  
http://cmsrailsatikp.herokuapp.com/  
  
  
are there any further steps i need to take eg: heroku rake db:migrate or  
something? i've even tried using the /categories/2 path as that is what i set  
as the homepage in the localhost server.  
  
  
i know i'm asking a lot but  
  
please advise  
  
  
thank you again  
  
  
kindest regards  
  
Atik Patel  
  
  
________________________________

**Pull request merged**
